package com.pojos;
// Generated 5 nov. 2019 19:38:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Carrera generated by hbm2java
 */
public class Carrera  implements java.io.Serializable {


     private int codigoCarrera;
     private Facultad facultad;
     private String nombre;
     private Integer cantidadUv;
     private Set estudiantes = new HashSet(0);

    public Carrera() {
    }

	
    public Carrera(int codigoCarrera) {
        this.codigoCarrera = codigoCarrera;
    }
    public Carrera(int codigoCarrera, Facultad facultad, String nombre, Integer cantidadUv, Set estudiantes) {
       this.codigoCarrera = codigoCarrera;
       this.facultad = facultad;
       this.nombre = nombre;
       this.cantidadUv = cantidadUv;
       this.estudiantes = estudiantes;
    }
   
    public int getCodigoCarrera() {
        return this.codigoCarrera;
    }
    
    public void setCodigoCarrera(int codigoCarrera) {
        this.codigoCarrera = codigoCarrera;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getCantidadUv() {
        return this.cantidadUv;
    }
    
    public void setCantidadUv(Integer cantidadUv) {
        this.cantidadUv = cantidadUv;
    }
    public Set getEstudiantes() {
        return this.estudiantes;
    }
    
    public void setEstudiantes(Set estudiantes) {
        this.estudiantes = estudiantes;
    }




}


