package com.pojos;
// Generated 5 nov. 2019 19:38:00 by Hibernate Tools 4.3.1



/**
 * Estudiante generated by hbm2java
 */
public class Estudiante  implements java.io.Serializable {


     private int codigoEstudiante;
     private Carrera carrera;
     private String nombre;
     private Integer edad;
     private String genero;
     private Double cumCiclo;
     private String direccion;
     private String telefonoMovil;

    public Estudiante() {
    }

	
    public Estudiante(int codigoEstudiante) {
        this.codigoEstudiante = codigoEstudiante;
    }
    public Estudiante(int codigoEstudiante, Carrera carrera, String nombre, Integer edad, String genero, Double cumCiclo, String direccion, String telefonoMovil) {
       this.codigoEstudiante = codigoEstudiante;
       this.carrera = carrera;
       this.nombre = nombre;
       this.edad = edad;
       this.genero = genero;
       this.cumCiclo = cumCiclo;
       this.direccion = direccion;
       this.telefonoMovil = telefonoMovil;
    }
   
    public int getCodigoEstudiante() {
        return this.codigoEstudiante;
    }
    
    public void setCodigoEstudiante(int codigoEstudiante) {
        this.codigoEstudiante = codigoEstudiante;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Double getCumCiclo() {
        return this.cumCiclo;
    }
    
    public void setCumCiclo(Double cumCiclo) {
        this.cumCiclo = cumCiclo;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }




}


