package com.pojos;
// Generated 5 nov. 2019 19:38:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad  implements java.io.Serializable {


     private int codigoFacultad;
     private String nombre;
     private String telefono;
     private Set carreras = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(int codigoFacultad) {
        this.codigoFacultad = codigoFacultad;
    }
    public Facultad(int codigoFacultad, String nombre, String telefono, Set carreras) {
       this.codigoFacultad = codigoFacultad;
       this.nombre = nombre;
       this.telefono = telefono;
       this.carreras = carreras;
    }
   
    public int getCodigoFacultad() {
        return this.codigoFacultad;
    }
    
    public void setCodigoFacultad(int codigoFacultad) {
        this.codigoFacultad = codigoFacultad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getCarreras() {
        return this.carreras;
    }
    
    public void setCarreras(Set carreras) {
        this.carreras = carreras;
    }




}


